plugins:
  message:
    name: redis
    options:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

# Using with a cluster
# plugins:
#   message:
#     name: redis
#     options:
#       nodes:
#         - host: <String>
#           port: <Number>
#           password: <String>
#         - host: <String>
#           port: <Number>
#       maxRedirections: 16
#       redisOptions:
#         password: 'fallback-password'
